name: Build and Deploy Element Plus

on:
  push:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --filter @packages/element-plus @packages/vue-utils

      - name: Build Vue Utils
        run: pnpm run build:vue-utils

      - name: Build Site
        run: pnpm run build:element-plus

      - name: Deploy to element-plus branch
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: ui-demi-docs
          folder: packages/element-plus/.vitepress/dist
          token: ${{ secrets.GITHUB_TOKEN }}
          repository-name: cc-hearts/ui-demi
          target-folder: element-plus
          single-commit: true
          clean: true
