name: Build and Deploy Element Plus

on:
  push:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i
      - name: Build Vue Utils
        run: pnpm run build:vue-utils

      - name: Build element-plus Site
        run: pnpm run build:element-plus

      - name: Deploy to element-plus packages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: ui-demi-docs
          folder: packages/element-plus/.vitepress/dist
          token: ${{ secrets.GITHUB_TOKEN }}
          repository-name: cc-hearts/ui-demi
          target-folder: element-plus
          single-commit: true
          clean: true

      - name: Build ant-design-vue Site
        run: pnpm run build:ant-design-vue

      - name: Deploy to ant-design-vue packages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: ui-demi-docs
          folder: packages/ant-design-vue/.vitepress/dist
          token: ${{ secrets.GITHUB_TOKEN }}
          repository-name: cc-hearts/ui-demi
          target-folder: ant-design-vue
          single-commit: true
          clean: true

      - name: Deploy to vue kit Site
        run: pnpm run build:vue-kit

      - name: Deploy to vue kit packages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: ui-demi-docs
          folder: packages/vue-kit/.vitepress/dist
          token: ${{ secrets.GITHUB_TOKEN }}
          repository-name: cc-hearts/ui-demi
          target-folder: vue-kit
          single-commit: true
          clean: true
